### ISSUE TITLE
Develop Phase 1

### ISSUE THREAD

**Issue by arunans23** [arunans23/DistributedFileSharing#3]
We are developing Phase 1 of the distributed file sharing system.
Features proposed

- Registration with Bootstrap server
- Creating a neighborhood (routing) table
- Creating interfaces for Ping and Pong messages 

If you want to contribute, put a comment in this issue and give a pull request. We will review it and accept it.

**Comment by arunans23** [comment]
@antrix190 yeah. sure. can you write some unit tests to test the functionality of code? One suitable class would be [BSClient](https://github.com/arunans23/DistributedFileSharing/blob/master/src/main/java/com/semicolon/ds/comms/BSClient.java).

**Comment by antrix190** [comment]
@arunans23 ??
